language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t shellyygtw/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shellyygtw/react-test npm test

after_success:
  - docker build -t shellyygtw/multi-client ./client
  - docker build -t shellyygtw/multi-nginx ./nginx
  - docker build -t shellyygtw/multi-server ./server
  - docker build -t shellyygtw/multi-worker ./worker
  # Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub.
  - docker push shellyygtw/multi-client
  - docker push shellyygtw/multi-nginx
  - docker push shellyygtw/multi-server
  - docker push shellyygtw/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-530329406526'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secrete_access_key: $AWS_SECRET_KEY